# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tatayaba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tatayaba

  target 'TatayabaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TatayabaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
