# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!

  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end

target 'Tatayaba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tatayaba
  pod 'Moya'
  pod 'SkyFloatingLabelTextField'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'SDWebImage'
  pod 'SwiftKeychainWrapper'
  pod 'MOLH'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'NewRelicAgent'
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  
  target 'TatayabaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TatayabaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
