# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Tatayaba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tatayaba
  pod 'Moya', '~> 12.0'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftKeychainWrapper', '~> 3.2.0'

  target 'TatayabaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TatayabaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
